AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: A Layer that packages the newest versions of aws-sdk and aws-xray-sdk

Metadata:
  AWS::ServerlessRepo::Application:
    Name: lambda-nodejs-custom-sdks-layer
    Description: A Lambda Layer that packages the newest versions of aws-sdk and aws-xray-sdk for nodejs8.10 functions
    Author: Solve HQ
    SpdxLicenseId: MIT
    LicenseUrl: LICENSE
    ReadmeUrl: README.md
    Labels: ["lambda", "layer", "sdks", "nodejs"]
    HomePageUrl: https://github.com/solve-hq/lambda-custom-sdks-layer
    SemanticVersion: 2.550.0
    SourceCodeUrl: https://github.com/solve-hq/lambda-custom-sdks-layer

Resources:
  nodejs:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./nodejs
      Handler: index.handler
      Runtime: nodejs8.10

  NodeJSLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      Description: A Layer that packages the newest versions of aws-sdk and aws-xray-sdk
      ContentUri: ./.aws-sam/build
      CompatibleRuntimes:
        - nodejs8.10
      LicenseInfo: "Available under the MIT-0 license."
      RetentionPolicy: Retain

Outputs:
  LayerVersionArn:
    Description: "The Layer Version ARN to use when setting the layers of a function"
    Value: !Ref NodeJSLayer
